//package rules;
//dialect  "mvel"
//
//import com.pointer.model.food.Beer;
//import com.pointer.main.Time;
//import com.pointer.model.buildings.Brewery;
//
//rule "Beer Production"
//  when
//      $t : Time()
//      $o : Breewry(($t.getDay() % day) == 0)
//   then
//     insert(new Beer())
//end
//
//
//rule "Beer Consumption"
//    when
//         $h : Happyness()
//         $t : Time()
//    then
//end
