package rules;
dialect  "mvel"

import com.pointer.main.Settlement;
import com.pointer.main.Time;
import com.pointer.model.Happyness;

rule "FoodConsumption"
     when
        $h : Happyness()
        $t : Time()
        $o : Settlement(getHappyness() == $h)
     then
        int n = $o.getNumberOfWorkers();
        double portionSize = $o.getGranary().getPortionSize();
        int happy = 0;

        if(portionSize == 1) {
            happy = 0;
        }
        if(portionSize == 0.75) {
            happy = -5;
        }
        if(portionSize == 1.25) {
            happy = 6;
        }
        System.out.println("PORCJA" + portionSize + " POZIOM ZADOWOLENIA" + $h.getHappyLevel());
        modify($h){ addHappy(happy)}

end
